name: generate my blog posts
on:
  issues:
    types: [opened, edited]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: junxnone/turn-issues-to-posts-action@master
        with:
          branch: "main" # default to main
          dir: "_posts" # default to _posts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          created_at: ${{ github.event.issue.created_at }}
          updated_at: ${{ github.event.issue.updated_at }}
          label_name: ${{ github.event.issue.label }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          actor: ${{ github.actor }}
